[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -DMICRO_ROS_TRANSPORT_ARDUINO_SERIAL
    -L"C:\projects\micro_ros_extract\micro_ros_arduino-2.0.7-humble\src\esp32"
    -lmicroros

lib_deps =
    file://C:\projects\micro_ros_extract\micro_ros_arduino-2.0.7-humble